# Generated by Django 3.2.3 on 2021-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to=''),
        ),
    ]
