# Generated by Django 4.2 on 2023-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_image_alter_book_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='../public/static/images/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_name',
            field=models.CharField(default='../public/static/images/default.jpg', max_length=50),
        ),
    ]
