# Generated by Django 4.2 on 2023-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_image_alter_book_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_name',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
