# Generated by Django 3.1.7 on 2021-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0003_auto_20210420_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
