# Generated by Django 3.1.7 on 2021-04-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0004_borrowing_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='date_string',
            new_name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='returned',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='date_returned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
