# Generated by Django 3.1.7 on 2021-05-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_borrowed'),
        ('borrowings', '0009_remove_borrowing_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
