# Generated by Django 3.1.7 on 2021-05-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0013_auto_20210513_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='book',
            new_name='book_field',
        ),
    ]
