# Generated by Django 3.1.7 on 2021-05-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_borrowed'),
        ('borrowings', '0017_auto_20210513_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
