# Generated by Django 4.2 on 2023-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0018_auto_20210513_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
